In [1]:
#!/usr/bin/env python

# Luis Enrique Coronado Zuniga
# You are free to use, change, or redistribute the code in any way you wish
# but please maintain the name of the original author.
# This code comes with no warranty of any kind.


#%%
import os
from numpy import*
from deep_hmpy import*
from hmpy import*
import timeit

dir_path = os.getcwd()
print dir_path
seed = 1

#Configuration of the models
create_models = False
features = False

#Define the name of the gesture
name_model1 = "bien_bateo"
name_model2 = "karate"
name_model3 = "espada"


# ************************************** Gesture, data and paths definitions *********************************************

#Define the path to save the models
path_to_save = dir_path + "/data/models/"

#Define the path of the gesture folders
path_to_load = dir_path + "/data/segmented_dnn/"

#Define id (name) of the files in the datatest, example <acc(1)>.txt, example <acc(2)>.txt , ....
files_id = "acc"

#Crate a new model
create_models = True

gest1 = GestureModel(name_model1,path_to_load,path_to_save)
gest2 = GestureModel(name_model2,path_to_load,path_to_save)
gest3 = GestureModel(name_model3,path_to_load,path_to_save)


#Create a list of models
list_models = [gest1,gest2,gest3]

value = pre1D.equal_inputs(list_models, "min")
print  "minimun value of samples: ",  value*3

if(create_models == True):
    gest1.buildDNN_model("3IMU_acc", features, value=value)
    gest2.buildDNN_model("3IMU_acc", features, value=value)
    gest3.buildDNN_model("3IMU_acc", features, value=value)

#Update list of models
list_models = [gest1,gest2,gest3]

# ******************************************** DNN training ***********************************************
from keras.models import Sequential
from keras.layers import Dense
import timeit
print "Libraries loaded"


dnn_dataset = concatenate((list_models[0].dnn_dataset,list_models[1].dnn_dataset), axis=0)
i = 2
n = size(list_models)

while(i < n):
    dnn_dataset = concatenate((dnn_dataset,list_models[i].dnn_dataset), axis=0)
    i = i + 1
X = dnn_dataset

print size(list_models[0].dnn_dataset)
print size(list_models[1].dnn_dataset)
print size(list_models[2].dnn_dataset)


#Outputs
n_classes = size(list_models)
training_examples1 = 15
Y = pre1D.set_outputs(n_classes,training_examples1)

print Y

n_examples, n_inputs = shape(X)
print shape(X)
print shape(Y)

random.seed(seed)
print "Data loaded"

#%%




Using Theano backend.
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


C:\Users\kike\Documents\GitHub\NEP-V5\packages\hmpy\examples

*************  Model =  bien_bateo ***********

C:\Users\kike\Documents\GitHub\NEP-V5\packages\hmpy\examples/data/segmented_dnn/bien_bateo
Number of samples: 15
Data correctly read and filtered

*************  Model =  karate ***********

C:\Users\kike\Documents\GitHub\NEP-V5\packages\hmpy\examples/data/segmented_dnn/karate
Number of samples: 15
Data correctly read and filtered

*************  Model =  espada ***********

C:\Users\kike\Documents\GitHub\NEP-V5\packages\hmpy\examples/data/segmented_dnn/espada
Number of samples: 15
Data correctly read and filtered
minimun value of samples:  171
Building a DNN model
Type Model = DNN , Type data= 3IMU_acc
dataset obtained
Building a DNN model
Type Model = DNN , Type data= 3IMU_acc
dataset obtained
Building a DNN model
Type Model = DNN , Type data= 3IMU_acc
dataset obtained
Libraries loaded
2520
2520
2520
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 

In [2]:
data = [[i for i in range(100)]]
data = np.array(data, dtype=float)
target = [[i for i in range(1,101)]]
target = np.array(target, dtype=float)

data = data.reshape((1, 1, 100)) 
target = target.reshape((1, 1, 100)) 
x_test=[i for i in range(100,200)]
x_test=np.array(x_test).reshape((1,1,100));
y_test=[i for i in range(101,201)]
y_test=np.array(y_test).reshape(1,1,100)


In [5]:
print data
print x_test
print y_test

[[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
    14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
    28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
    42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
    56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
    70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
    84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
    98.  99.]]]
[[[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
   118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
   136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
   154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
   172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
   190 191 192 193 194 195 196 197 198 199]]]
[[[101 102 103 104 105 106 107 108 109 110 111 112 1

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

model = Sequential()  
model.add(LSTM(100, input_shape=(1, 100),return_sequences=True))
model.add(Dense(100))

tic=timeit.default_timer()
model.compile(loss='mean_absolute_error', optimizer='adam',metrics=['accuracy'])

model.fit(data, target, nb_epoch=10, batch_size=1, verbose=2,validation_data=(X, Y))

toc=timeit.default_timer()
tm = toc -tic

print "Fit complete in" , toc - tic , "seconds"